require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - /config/**/*.*
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Rails/FilePath:
  Enabled: false
